Buscor/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Home, Authentication, and General Views
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('success/', views.success, name='success'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('about/', views.about, name='about'),
    path('book-bus/', views.book_bus, name='book_bus'),

    # Messages Views
    path('messages/', views.messages_list, name='messages_list'),
    path('messages/<int:message_id>/', views.message_detail, name='message_detail'),
]

Buscor/project/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import home  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),  
    path('app/', include('app.urls')),
    path('', include('django.contrib.auth.urls')),
]

Buscor/app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# SignUpForm for user registration
class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(
        widget=forms.PasswordInput,
        label="Password"
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput,
        label="Confirm Password"
    )
    name = forms.CharField(max_length=30, label="Name")
    surname = forms.CharField(max_length=30, label="Surname")
    id_number = forms.CharField(max_length=20, label="ID Number")
    phone = forms.CharField(max_length=15, label="Phone Number")

    class Meta:
        model = User
        fields = ('username',)
    
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords do not match.")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

# MessageFilterForm for filtering messages
class MessageFilterForm(forms.Form):
    MESSAGE_TYPE_CHOICES = [
        ('', 'All'),
        ('booking', 'Booking Confirmation'),
        ('promotion', 'Promotional Offer'),
        ('service', 'Service Alert'),
        ('support', 'Customer Support'),
        ('feedback', 'Feedback Request'),
        ('general', 'General Announcement'),
    ]
    
    message_type = forms.ChoiceField(choices=MESSAGE_TYPE_CHOICES, required=False)
    search = forms.CharField(max_length=100, required=False)

Buscor/app/templates/about.html
{% load static %}

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<!-- 
THEME: Constra - Construction Html5 Template
VERSION: 1.0.0
AUTHOR: Themefisher

HOMEPAGE: https://themefisher.com/products/constra-construction-template/
DEMO: https://demo.themefisher.com/constra/
GITHUB: https://github.com/themefisher/Constra-Bootstrap-Construction-Template

WEBSITE: https://themefisher.com
TWITTER: https://twitter.com/themefisher
FACEBOOK: https://www.facebook.com/themefisher
-->

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
================================================== -->
  <meta charset="utf-8">
  <title>About us </title>

  <!-- Mobile Specific Metas
================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Construction Html5 Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name=author content="Themefisher">
  <meta name=generator content="Themefisher Constra HTML Template v1.0">

  <!-- Favicon
================================================== -->
<link rel="icon" type="image/png" href="{% static 'images/bus1.png' %}">

  <!-- CSS
================================================== -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/bootstrap.min.css' %}">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}">
    <!-- Animation -->
    <link rel="stylesheet" href="{% static 'assets/plugins/animate-css/animate.css' %}">
    <!-- slick Carousel -->
    <link rel="stylesheet" href="{% static 'assets/plugins/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/slick/slick-theme.css' %}">
    <!-- Colorbox -->
    <link rel="stylesheet" href="{% static 'assets/plugins/colorbox/colorbox.css' %}">
    <!-- Template styles-->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

</head>
<body>
  <div class="body-inner">

    <div id="top-bar" class="top-bar">
        <div class="container">
          <div class="row">
              <div class="col-lg-8 col-md-8">
                <ul class="top-info text-center text-md-left">
                    
                </ul>
              </div>
              <!--/ Top info end -->
  
              <div class="col-lg-4 col-md-4 top-social text-center text-md-right">
                <ul class="list-unstyled">
                    <li>
                      <a title="Facebook" href="https://facebbok.com/themefisher.com">
                          <span class="social-icon"><i class="fab fa-facebook-f"></i></span>
                      </a>
                      <a title="Twitter" href="https://twitter.com/themefisher.com">
                          <span class="social-icon"><i class="fab fa-twitter"></i></span>
                      </a>
                      <a title="Instagram" href="https://instagram.com/themefisher.com">
                          <span class="social-icon"><i class="fab fa-instagram"></i></span>
                      </a>
                      <a title="Linkdin" href="https://github.com/themefisher.com">
                          <span class="social-icon"><i class="fab fa-github"></i></span>
                      </a>
                    </li>
                </ul>
              </div>
              <!--/ Top social end -->
          </div>
          <!--/ Content row end -->
        </div>
        <!--/ Container end -->
    </div>
    <!--/ Topbar end -->
<!-- Header start -->
<header id="header" class="header-one">
    <div class="bg-white">
      <div class="container">
        <div class="logo-area">
            <div class="row align-items-center">
              <div class="logo col-lg-3 text-center text-lg-left mb-3 mb-md-5 mb-lg-0">
                  <a class="d-block" href="{% static 'assets/index.html' %}">
                    <img loading="lazy" src="{% static 'assets/ump1.png' %}" alt="UMP Buscor">
                    <img loading="lazy" src="{%static 'assets/bus1.png' %}" alt="UMP Buscor">
                  </a>
            </div><!-- logo end -->
  
            
            <div class="col-lg-9 header-right">
              <ul class="top-info-box">
                <li>
                  <div class="info-box">
                    <div class="info-box-content">
                        <p class="info-box-title">Call Us</p>
                        <p class="info-box-subtitle">(+27) 83-400-4353</p>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="info-box">
                    <div class="info-box-content">
                        <p class="info-box-title">Email Us</p>
                        <p class="info-box-subtitle">BuscorWebapp@gmail.com</p>
                    </div>
                  </div>
                </li>
                
                <li class="header-get-a-quote">
                  <a class="btn btn-primary" href="signup.html">Sign-up</a>
                  <a class="btn btn-primary" href="contact.html">Sign-in</a>
                </li>
                </ul><!-- Ul end -->
            </div><!-- header right end -->
          </div><!-- logo area end -->
  
      </div><!-- Row end -->
    </div><!-- Container end -->
  </div>

  <div class="site-navigation">
    <div class="container">
        <div class="row">
          <div class="col-lg-12">
              <nav class="navbar navbar-expand-lg navbar-dark p-0">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div id="navbar-collapse" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav mr-auto">
                      <li class="nav-item"><a class="nav-link" href="about.html">About us</a></li>
                    </ul>
                </div>
              </nav>
          </div>
          <!--/ Col end -->
        </div>
        <!--/ Row end -->

        <div class="search-block" style="display: none;">
          <label for="search-field" class="w-100 mb-0">
            <input type="text" class="form-control" id="search-field" placeholder="Type what you want and enter">
          </label>
          <span class="search-close">&times;</span>
        </div><!-- Site search end -->
    </div>
    <!--/ Container end -->

  </div>
  <!--/ Navigation end -->
</header>
<!--/ Header end -->
<div class="carousel-item banner-carousel-item" style="background-image: url('{% static "assets\bus11.jpg" %}');">
  <div class="banner-text">
    <div class="container">
        <div class="row">
          <div class="col-lg-12">
              <div class="banner-heading">
                <h1 class="banner-title">About</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                      <li class="breadcrumb-item"><a href="#">Home</a></li>
                      <li class="breadcrumb-item"><a href="#">company</a></li>
                      <li class="breadcrumb-item active" aria-current="page">About Us</li>
                    </ol>
                </nav>
              </div>
          </div><!-- Col end -->
        </div><!-- Row end -->
    </div><!-- Container end -->
  </div><!-- Banner text end -->
</div><!-- Banner area end --> 

<section id="main-container" class="main-container">
  <div class="container">
    <div class="row">
        <div class="col-lg-6">
          <h3 class="column-title">Who We Are</h3>
          <p>We are final year students, From the university of Mpumalanga, we are doing diploma in information communication technology and this is our web application</p>
          <blockquote><p>we trive for a better future</p></blockquote>
          <p>this is us 
            Man Man group learder,
            nonhle fornt end developer,
            Bongani front end developer,
            kieneilwe back end developer,
            calvin back end developer,
            france back end developer
          </p>

        </div><!-- Col end -->

        <div class="col-lg-6 mt-5 mt-lg-0">
          
          <div id="page-slider" class="page-slider small-bg">

              <div class="item" style="background-image:url(LEADERSHIP.webp)">
                <div class="container">
                    <div class="box-slider-content">
                      <div class="box-slider-text">
                          <h2 class="box-slide-title">Leadership</h2>
                      </div>    
                    </div>
                </div>
              </div><!-- Item 1 end -->

              <div class="item" style="background-image:url(images/slider-pages/slide-page2.jpg)">
                <div class="container">
                    <div class="box-slider-content">
                      <div class="box-slider-text">
                          <h2 class="box-slide-title">Relationships</h2>
                      </div>    
                    </div>
                </div>
              </div><!-- Item 1 end -->

              <div class="item" style="background-image:url(images/performance.jpg)">
                <div class="container">
                    <div class="box-slider-content">
                      <div class="box-slider-text">
                          <h2 class="box-slide-title">Performance</h2>
                      </div>    
                    </div>
                </div>
              </div><!-- Item 1 end -->
          </div><!-- Page slider end-->          
        

        </div><!-- Col end -->
    </div><!-- Content row end -->

  </div><!-- Container end -->
</section><!-- Main container end -->



<footer id="footer" class="footer bg-overlay">
  <div class="footer-main">
    <div class="container">
      <div class="row justify-content-between">
        <div class="col-lg-4 col-md-6 footer-widget footer-about">
          <h3 class="widget-title">UMP BASCOR WEB APP</h3>
          <img loading="lazy" width="200px" class="footer-logo" src="{% static 'assets/logo2.png' %}" alt="The UMP Buscor Web Application">
          <p>Get your bus ticket with just the click of button , Easy and hussle free.</p>
          <div class="footer-social">
            <ul>
              <li><a href="hps:/facok.com/themefisher" aria-label="Facebook"><i
                    class="fab fa-facebook-f"></i></a></li>
              <li><a href="hps:/twiter.com/themefisher" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
              </li>
              <li><a href="hs:/instagram.com/themefisher" aria-label="Instagram"><i
                    class="fab fa-instagram"></i></a></li>
              <li><a href="hps:/giub.com/themefisher" aria-label="Github"><i class="fab fa-github"></i></a></li>
            </ul>
          </div><!-- Footer social end -->
        </div><!-- Col end -->

        <div class="col-lg-4 col-md-6 footer-widget mt-5 mt-md-0">
          <h3 class="widget-title">Working Hours</h3>
          <div class="working-hours">
            We work 7 days a week, every day excluding major holidays. Contact us if you have an emergency, with our
            Hotline and Contact form.
            <br><br> Monday - Friday: <span class="text-right">10:00 - 16:00 </span>
            <br> Saturday: <span class="text-right">12:00 - 15:00</span>
            <br> Sunday and holidays: <span class="text-right">09:00 - 12:00</span>
          </div>
        </div><!-- Col end -->

      </div><!-- Row end -->
    </div><!-- Container end -->
  </div><!-- Footer main end -->

  <div class="copyright">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-6">
          <div class="copyright-info">
            <span>Copyright &copy; <script>
                document.write(new Date().getFullYear())
              </script>, Designed &amp; Developed by <a href="">GROUP G</a></span>
          </div>
        </div>

        <div class="col-md-6">
          <div class="footer-menu text-center text-md-right">
            <ul class="list-unstyled">
              <li><a href="about.html">About</a></li>
             
            </ul>
          </div>
        </div>
      </div><!-- Row end -->

      <div id="back-to-top" data-spy="affix" data-offset-top="10" class="back-to-top position-fixed">
        <button class="btn btn-primary" title="Back to Top">
          <i class="fa fa-angle-double-up"></i>
        </button>
      </div>

    </div><!-- Container end -->
  </div><!-- Copyright end -->
</footer><!-- Footer end -->


  <!-- Javascript Files
  ================================================== -->

  <!-- initialize jQuery Library -->
  <script src="plugins/jQuery/jquery.min.js"></script>
  <!-- Bootstrap jQuery -->
  <script src="plugins/bootstrap/bootstrap.min.js" defer></script>
  <!-- Slick Carousel -->
  <script src="plugins/slick/slick.min.js"></script>
  <script src="plugins/slick/slick-animation.min.js"></script>
  <!-- Color box -->
  <script src="plugins/colorbox/jquery.colorbox.js"></script>
  <!-- shuffle -->
  <script src="plugins/shuffle/shuffle.min.js" defer></script>


  <!-- Google Map API Key-->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU" defer></script>
  <!-- Google Map Plugin-->
  <script src="plugins/google-map/map.js" defer></script>

  <!-- Template custom -->
  <script src="js/script.js"></script>

  </div><!-- Body inner end -->
  </body>

  </html>

Buscor/app/templates/messages.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Messages</title>
    <!-- Add any CSS or JS links here -->
</head>
<body>
    <div class="container">
        <h2>Messages</h2>

        <!-- Display the unread messages count -->
        <div class="unread-indicator">
            <p>You have {{ unread_count }} unread message(s)</p>
        </div>

        <!-- Add the filter/search form here -->
        <form method="GET">
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>

        <!-- List messages -->
        <ul class="message-list">
            {% for message in messages %}
            <li class="{% if not message.is_read %}unread{% endif %}">
                <a href="{% url 'message_detail' message.id %}">
                    <strong>{{ message.subject }}</strong>
                    <p>{{ message.created_at|date:"M d, Y H:i" }}</p>
                </a>
            </li>
            {% empty %}
            <p>No messages to display.</p>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

Buscor/app/templates/messages_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ message.subject }}</title>
    <!-- Add any CSS or JS links here -->
</head>
<body>
    <div class="container">
        <h2>{{ message.subject }}</h2>
        <p>{{ message.created_at|date:"M d, Y H:i" }}</p>
        <hr>
        <p>{{ message.body }}</p>

        <a href="{% url 'messages_list' %}" class="btn btn-primary">Back to Messages</a>
    </div>
</body>
</html>

Buscor/app/templates/payment_success.html
{% load static %}
<!-- payment_success.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Successful!</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            text-align: center;
        }

        h1 {
            color: #4CAF50;
            margin-bottom: 20px;
        }

        #qr-code-container {
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
            background-color: white;
            border-radius: 12px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        #qr-code {
            width: 256px;
            height: 256px;
            border-radius: 12px;
            overflow: hidden;
        }

        p {
            color: #777;
            font-size: 14px;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <h1>Payment Successful!</h1>
    <div id="qr-code-container">
        <div id="qr-code"></div>
    </div>
    <p style="display: none;" id="unique_qr_code_text">{{ unique_qr_code_text }}</p>
    <script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"></script>
    <script>
        // Function to generate QR code
        function generateQRCode(text) {
            new QRCode(document.getElementById("qr-code"), {
                text: text,
                width: 256,
                height: 256,
            });
        }

        // Get the unique QR code text from the hidden paragraph
        const unique_qr_code_text = document.getElementById("unique_qr_code_text").innerText;

        // Generate the QR code using the unique text
        generateQRCode(unique_qr_code_text);
    </script>
</body>
</html>

Buscor/app/templates/qrcode.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QR Code Generator</title>
    <script src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 50px;
        }
        #qrcode {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>QR Code Generator</h1>
    <div id="qrcode"></div>

    <script>
        // Function to get URL parameters
        function getURLParams() {
            const params = new URLSearchParams(window.location.search);
            const paramsObj = {};
            for (const [key, value] of params.entries()) {
                paramsObj[key] = value;
            }
            return paramsObj;
        }

        // Generate QR code from URL parameters
        function generateQRCode(text) {
            new QRCode(document.getElementById("qrcode"), {
                text: text,
                width: 256,
                height: 256,
            });
        }

        // Get URL parameters and convert them to a string
        const params = getURLParams();
        const paramsString = JSON.stringify(params);

        // Generate the QR code based on the URL parameters
        if (paramsString !== '{}') {
            generateQRCode(paramsString);
        } else {
            document.getElementById("qrcode").innerText = "No parameters found in URL";
        }
    </script>
</body>
</html>

Buscor/app/templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <style>
        /* Global Reset and Body Styling */
        body {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: url('{% static "assets/wave.jpg" %}') no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden; /* Prevents body from scrolling */
        }

        .container {
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            height: 100%;
            padding: 10px;
            box-sizing: border-box;
        }

        .signup-form {
            background: rgba(255, 255, 255, 0.95);
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 450px;
            box-sizing: border-box;
            overflow-y: auto; /* Enables scrollbar */
            max-height: 90vh; /* Limits height */
        }

        .signup-form h1 {
            margin: 0 0 15px;
            color: #333;
            font-size: 1.8rem;
            text-align: center;
            font-weight: 600;
        }

        .signup-form ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .signup-form li {
            margin-bottom: 15px;
        }

        .signup-form label {
            display: block;
            margin-bottom: 5px;
            font-weight: 500;
            color: #444;
            font-size: 14px;
        }

        .signup-form input[type="text"],
        .signup-form input[type="password"],
        .signup-form input[type="number"],
        .signup-form input[type="tel"] {
            width: 100%;
            padding: 10px 12px;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 14px;
            box-sizing: border-box;
            transition: border-color 0.3s ease;
        }

        .signup-form input[type="text"]:focus,
        .signup-form input[type="password"]:focus,
        .signup-form input[type="number"]:focus,
        .signup-form input[type="tel"]:focus {
            border-color: #007bff;
            outline: none;
            box-shadow: 0 0 3px rgba(0, 123, 255, 0.25);
        }

        .signup-form input[type="submit"] {
            background: linear-gradient(45deg, #007bff, #0056b3);
            color: white;
            border: none;
            padding: 12px 0;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            width: 100%;
            transition: background 0.3s ease, transform 0.3s ease;
            box-sizing: border-box;
        }

        .signup-form input[type="submit"]:hover {
            background: linear-gradient(45deg, #0056b3, #004494);
            transform: scale(1.02);
        }

        .signup-form p {
            margin-top: 15px;
            color: #666;
            text-align: center;
            font-size: 14px;
        }

        .signup-form a {
            color: #007bff;
            text-decoration: none;
            font-weight: 600;
        }

        .signup-form a:hover {
            text-decoration: underline;
            color: #0056b3;
        }

        /* Custom scrollbar styling */
        .signup-form::-webkit-scrollbar {
            width: 8px;
        }

        .signup-form::-webkit-scrollbar-track {
            background: #f1f1f1;
            border-radius: 10px;
        }

        .signup-form::-webkit-scrollbar-thumb {
            background: #888;
            border-radius: 10px;
        }

        .signup-form::-webkit-scrollbar-thumb:hover {
            background: #555;
        }

        .error-message {
            color: red;
            font-size: 12px;
        }
    </style>
    <script>
        function validateForm() {
            // Password Validation: At least 8 characters, with at least 1 special character or number
            const password = document.getElementById('id_password1').value;
            const passwordPattern = /^(?=.*[0-9!@#$%^&*])(?=.{8,})/;

            // ID Validation: Must be exactly 13 digits
            const idNumber = document.getElementById('id_id_number').value;
            const idPattern = /^\d{13}$/;

            let isValid = true;

            // Validate Password
            if (!passwordPattern.test(password)) {
                document.getElementById('password-error').textContent = 'Password must be at least 8 characters long and include at least 1 special character or number.';
                isValid = false;
            } else {
                document.getElementById('password-error').textContent = '';
            }

            // Validate South African ID Number
            if (!idPattern.test(idNumber)) {
                document.getElementById('id-error').textContent = 'ID Number must be exactly 13 digits.';
                isValid = false;
            } else {
                document.getElementById('id-error').textContent = '';
            }

            return isValid;
        }
    </script>
</head>
<body>
    <div class="container">
        <div class="signup-form">
            <h1>Sign Up</h1>
            <form method="post" action="{% url 'signup' %}" onsubmit="return validateForm();">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <ul>
                    <li>
                        <label for="id_username">Username:</label>
                        {{ form.username }}
                        {{ form.username.errors }}
                    </li>
                    <li>
                        <label for="id_password1">Password:</label>
                        {{ form.password1 }}
                        <span class="error-message" id="password-error"></span>
                        {{ form.password1.errors }}
                    </li>
                    <li>
                        <label for="id_password2">Confirm Password:</label>
                        {{ form.password2 }}
                        {{ form.password2.errors }}
                    </li>
                    <li>
                        <label for="id_name">Name:</label>
                        {{ form.name }}
                        {{ form.name.errors }}
                    </li>
                    <li>
                        <label for="id_surname">Surname:</label>
                        {{ form.surname }}
                        {{ form.surname.errors }}
                    </li>
                    <li>
                        <label for="id_id_number">ID Number:</label>
                        {{ form.id_number }}
                        <span class="error-message" id="id-error"></span>
                        {{ form.id_number.errors }}
                    </li>
                    <li>
                        <label for="id_phone">Phone Number:</label>
                        {{ form.phone }}
                        {{ form.phone.errors }}
                    </li>
                </ul>
                <input type="submit" value="Sign Up">
            </form>
            <p>Already have an account? <a href="{% url 'signin' %}">Sign In</a></p>
        </div>
    </div>
</body>
</html>

Buscor/app/templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <title>Signup Successful</title>
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        </header>
        <div class="main-content">
            <h1>Registration Successful!</h1>
            <p><a href="{% url 'signin' %}">Click here to login</a></p>
        </div>
        <footer class="footer">
            &copy; 2023 Tech Wizards. All Rights Reserved.
        </footer>
    </div>
</body>
</html>